# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

"""
Train XGBoost multi-class classifier for campaign diagnosis.

Reads:   ml/data/training_data.csv
Writes:
    ml/model/diagnosis_model.pkl   — trained XGBClassifier
    ml/model/label_encoder.pkl     — maps class names <-> integer labels
    ml/model/feature_names.json    — ordered list of feature column names

Run:
    python ml/train_model.py

Requirements:
    pip install xgboost scikit-learn pandas joblib
"""
import json
from pathlib import Path

import joblib
import pandas as pd
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from xgboost import XGBClassifier

FEATURE_COLS = [
    "bid_to_floor_ratio",
    "win_rate",
    "delivery_pct",
    "expected_pct",
    "delivery_variance",
    "days_elapsed_pct",
    "days_remaining",
    "competitor_count",
    "competitor_change_24h",
    "demand_supply_ratio",
    "cpm_change_pct",
    "ctr",
    "industry_encoded",
    "geo_encoded",
    "budget_consumed_pct",
]

LABEL_COL = "issue_type"


def train(data_path: Path, model_dir: Path):
    """
    Train an XGBoost multi-class classifier and save the artifacts to disk.

    Steps performed:
    1. Load the CSV generated by generate_training_data.py.
    2. Encode string labels to integers using LabelEncoder (required by XGBoost).
    3. Split 80/20 train/test, stratified so each class has equal representation
       in both splits.
    4. Train XGBClassifier with 200 trees, max depth 5, learning rate 0.1.
    5. Print test accuracy, per-class precision/recall/F1, and top-10 feature
       importances so you can evaluate model quality before deploying.
    6. Save three artifacts to model_dir/:
       - diagnosis_model.pkl   (the trained XGBClassifier)
       - label_encoder.pkl     (maps "bid_too_low" <-> integer 0, etc.)
       - feature_names.json    (ordered list of feature columns — used by
                                diagnose_campaign_ml.py to build the input vector)

    Args:
        data_path: Path to training_data.csv.
        model_dir: Directory where model artifacts will be written.

    Returns:
        Tuple[XGBClassifier, LabelEncoder]: The trained model and its label encoder.
    """
    model_dir.mkdir(exist_ok=True)

    # --- Load data ---
    df = pd.read_csv(data_path)
    print(f"Loaded {len(df)} rows")
    print(f"\nClass distribution:\n{df[LABEL_COL].value_counts().to_string()}\n")

    # --- Encode string labels to integers (XGBoost requires numeric labels) ---
    le = LabelEncoder()
    y = le.fit_transform(df[LABEL_COL])
    X = df[FEATURE_COLS]

    print(f"Classes: {list(le.classes_)}\n")

    # --- Train / test split (80/20, stratified so each class is proportional) ---
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.20, random_state=42, stratify=y
    )

    # --- Train ---
    model = XGBClassifier(
        n_estimators=200,
        max_depth=5,
        learning_rate=0.1,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
    )
    model.fit(X_train, y_train)

    # --- Evaluate ---
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print(f"Test accuracy: {acc:.3f}\n")
    print("Per-class performance:")
    print(classification_report(y_test, y_pred, target_names=le.classes_))

    # --- Feature importance ---
    importance = sorted(
        zip(FEATURE_COLS, model.feature_importances_),
        key=lambda x: x[1], reverse=True
    )
    print("Feature importance (top 10):")
    for feat, score in importance[:10]:
        print(f"  {feat:30s}  {score:.4f}")

    # --- Save artifacts ---
    model_path   = model_dir / "diagnosis_model.pkl"
    le_path      = model_dir / "label_encoder.pkl"
    feature_path = model_dir / "feature_names.json"

    joblib.dump(model, model_path)
    joblib.dump(le, le_path)
    with open(feature_path, "w", encoding="utf-8") as f:
        json.dump(FEATURE_COLS, f, indent=2)

    print(f"\nSaved model    -> {model_path}")
    print(f"Saved encoder  -> {le_path}")
    print(f"Saved features -> {feature_path}")

    return model, le


def main():
    """
    Entry point: resolve paths and call train().

    Exits with an error message if training_data.csv is missing,
    directing the user to run generate_training_data.py first.
    """
    base      = Path(__file__).parent
    data_path = base / "data" / "training_data.csv"
    model_dir = base / "model"

    if not data_path.exists():
        print(f"ERROR: {data_path} not found.")
        print("Run first:  python ml/generate_training_data.py")
        return

    train(data_path, model_dir)


if __name__ == "__main__":
    main()
